# Generated by Django 2.1.1 on 2018-10-22 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='purchased',
            field=models.CharField(choices=[('sku_DoNhM1EGgKGLeg', '1 Post'), ('sku_DoNp2frdbkieqn', '12 Posts'), ('plan_DoNu8JmqFRMrze', 'Unlimited Posts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
