# Generated by Django 2.1.1 on 2018-09-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='post_image')),
                ('email', models.CharField(max_length=35)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('applicationInbox', models.CharField(max_length=35)),
                ('password', models.CharField(default='', max_length=100)),
                ('isEmployee', models.BooleanField(default=False)),
                ('isActive', models.BooleanField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ('published_date',)},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
