# Generated by Django 2.1.1 on 2018-09-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180912_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('published_date',)},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ('published_date',)},
        ),
        migrations.AddField(
            model_name='employee',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
