# Generated by Django 2.1.1 on 2018-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180912_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
