# Generated by Django 2.1.1 on 2018-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180913_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='appsInbox',
            new_name='apps_inbox',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='isEmployer',
            new_name='is_employer',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='applicationInbox',
            new_name='application_inbox',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='isEmployee',
            new_name='is_employee',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
