# Generated by Django 2.1.1 on 2018-09-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
