# Generated by Django 2.1.1 on 2018-09-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20180913_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
