# Generated by Django 2.1.1 on 2018-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20180914_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
